#!/usr/bin/env bash
set -euo pipefail

watchdir="$1"
target="$2"

while true; do
    before=$(ls -1 | wc -l)
    # Don't use -a because we want copied files to have an updated modified date.
    # Exclude FlashAir default image needed for manual Wi-Fi toggling
    rsync -vr --size-only --exclude 'FA000001.JPG' "$watchdir" "$target"
    after=$(ls -1 | wc -l)
    if ((after > before)); then
        make preview
    fi
    sleep 2
done
